# src/MagBundle/Resources/config/doctrine/articles.orm.yml
MagBundle\Entity\articles:
    type: entity
    table: articles
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 32
        article_type: 
             type: string
             length: 20
        producer:     
            type: text
            nullable: true
        wallper:
             type: text
             nullable: TRUE
        article_id:
            type: integer
        barcode:
             type: integer
        views:
            type: integer
        price:
            type: integer
        stock:
            type: integer
        